const $=(s)=>document.querySelector(s);const $$=(s)=>[...document.querySelectorAll(s)];
const lessons=[
{id:'yamal-permafrost',region:'ЯНАО / Арктика',tag:'ЯМАЛ',title:'Вечная мерзлота: что происходит с грунтом?',text:'Как измеряют сезонное протаивание, почему одна точка наблюдений не описывает весь полуостров и что здесь важно знать о климате.',level:'Средний',source:'Oblogov et al., 2020, Geosciences; наблюдения станции Марре-Сале.',url:'https://doi.org/10.3390/geosciences10100412'},
{id:'yamal-methane',region:'ЯНАО / Арктика',tag:'ЯМАЛ',title:'Метан тундры: источник или ловушка?',text:'Разбираем, откуда берётся метан в тундровых экосистемах и почему выводы зависят от масштаба измерений.',level:'Сложный',source:'Oblogov et al., 2020, Geosciences; западный Ямал.',url:'https://doi.org/10.3390/geosciences10100412'},
{id:'yamal-reindeer',region:'ЯНАО / Арктика',tag:'ЯМАЛ',title:'Оленеводство и меняющийся Север',text:'Как климат и выпас связаны с изменениями растительности Ямала и почему пространственный масштаб исследования важен.',level:'Средний',source:'Spiegel et al., 2023, Earth’s Future; исследование 67 000 км² Ямала.',url:'https://doi.org/10.1029/2022EF003407'},
{id:'volga-eutrophication',region:'Россия / Волга',tag:'РОССИЯ',title:'Почему цветёт вода?',text:'Эвтрофикация: питательные вещества, водоросли, кислород и почему река может менять состояние целой экосистемы.',level:'Начальный',source:'OECD, Environment at a Glance; научная литература по эвтрофикации.',url:'https://www.oecd.org/environment/'},
{id:'black-sea',region:'Россия / Чёрное море',tag:'РОССИЯ',title:'Море под слоем пластика?',text:'Что действительно можно сказать о пластиковом загрязнении морской среды и как устроен мониторинг.',level:'Средний',source:'UNEP, From Pollution to Solution; глобальная оценка морского мусора.',url:'https://www.unep.org/resources/pollution-solution-global-assessment-marine-litter-and-plastic-pollution'},
{id:'baikal',region:'Россия / Байкал',tag:'РОССИЯ',title:'Байкал: почему прозрачность — не вся история',text:'Прозрачная вода не означает, что экосистема не меняется. Разбираем мониторинг, водоросли и пищевые сети.',level:'Средний',source:'Limnology and Freshwater Biology; научные исследования озера Байкал.',url:'https://limnolfreshwaterbiol.com/'},
{id:'peatlands',region:'Сибирь / болота',tag:'МИР',title:'Болото — не пустошь',text:'Торфяники накапливают углерод тысячелетиями. Что происходит при осушении и пожарах.',level:'Начальный',source:'IPCC Wetlands Supplement.',url:'https://www.ipcc-nggip.iges.or.jp/public/wetlands/'},
{id:'arctic-sea-ice',region:'Арктика',tag:'МИР',title:'Лёд, который меняет карту климата',text:'Морской лёд отражает солнечную радиацию и взаимодействует с атмосферой и океаном. Как читают спутниковые ряды.',level:'Средний',source:'NSIDC Sea Ice Index.',url:'https://nsidc.org/data/seaice_index/'},
{id:'ocean-acid',region:'Мировой океан',tag:'МИР',title:'Океан становится кислее?',text:'pH, растворённый CO₂ и химия морской воды без пугающих упрощений.',level:'Средний',source:'NOAA Ocean Acidification Program.',url:'https://oceanacidification.noaa.gov/'},
{id:'food-waste',region:'Глобально',tag:'МИР',title:'Еда, которую никто не съел',text:'Почему пищевые потери возникают на разных этапах цепочки и как не перепутать отходы с потерями.',level:'Начальный',source:'FAO; UNEP Food Waste Index.',url:'https://www.unep.org/resources/report/food-waste-index-report-2024'},
{id:'urban-heat',region:'Города мира',tag:'МИР',title:'Почему асфальт горячее дерева?',text:'Городской остров тепла: поверхности, тень, испарение и дизайн улиц.',level:'Начальный',source:'IPCC AR6 WGII.',url:'https://www.ipcc.ch/report/ar6/wg2/'},
{id:'e-waste',region:'Глобально',tag:'МИР',title:'Электроника после жизни',text:'Почему электронный мусор ценен как ресурс и опасен при неправильном обращении.',level:'Средний',source:'UNITAR/ITU Global E-waste Monitor 2024.',url:'https://ewastemonitor.info/'},
];
const questions=[
{q:'Что означает «сезонное протаивание» в исследованиях мерзлоты?',a:['Глубину океана летом','Максимальную глубину оттаявшего за сезон слоя над мерзлотой','Температуру воздуха за сезон','Скорость таяния морского льда'],c:1,d:1,t:'ЯНАО',e:'Средний слой, оттаивающий летом над многолетнемёрзлым грунтом, называют активным слоем.'},
{q:'Почему один датчик не может описать всю тундру?',a:['Датчики всегда ошибаются','Почвы, растительность, влажность и рельеф пространственно различаются','Потому что в тундре нет GPS','Потому что температура везде одинаковая'],c:1,d:1,t:'ЯНАО',e:'Пространственная неоднородность — одна из ключевых причин сети наблюдений.'},
{q:'Какой признак сильнее всего повышает доверие к числу в экологической статистике?',a:['Красивый график','Большое число знаков после запятой','Понятная методика, единицы, период и источник данных','Эмоциональный заголовок'],c:2,d:0,t:'Метод',e:'Число без контекста почти ничего не говорит.'},
{q:'Что такое эвтрофикация?',a:['Остывание океана','Обогащение воды питательными веществами, способное вызвать чрезмерный рост водорослей','Миграция рыб','Испарение воды'],c:1,d:0,t:'Россия',e:'Избыток азота и фосфора может запускать каскад экологических изменений.'},
{q:'Почему океан закисляется при росте CO₂ в атмосфере?',a:['CO₂ напрямую превращается в соль','CO₂ растворяется в морской воде и участвует в системе карбонатного равновесия','Океан перестаёт испаряться','Соль исчезает'],c:1,d:1,t:'Мир',e:'Растворение CO₂ меняет химическое равновесие морской воды и снижает pH.'},
{q:'Что правильнее всего сказать о пищевых отходах?',a:['Все потери происходят дома','Потери возникают на разных стадиях цепочки от производства до потребления','Их невозможно измерить','Это только испорченная еда в магазинах'],c:1,d:0,t:'Мир',e:'UNEP и FAO разделяют потери и отходы по этапам цепочки.'},
{q:'Что делает спутниковый ряд особенно полезным для экологии?',a:['Он всегда заменяет наземные измерения','Он позволяет наблюдать большие территории и изменения во времени','Он не имеет погрешности','Он показывает причины явления напрямую'],c:1,d:1,t:'Метод',e:'Спутники дают пространственную и временную картину, но требуют валидации и интерпретации.'},
{q:'Что происходит с торфяником при осушении?',a:['Он автоматически становится лесом','Меняется водный режим, усиливается разложение органики и меняются потоки углерода','Ничего','Он перестаёт содержать органику'],c:1,d:2,t:'Сложно',e:'Эффекты зависят от климата, типа торфа, глубины осушения и последующего землепользования.'},
{q:'Какой вопрос является проверяемой гипотезой?',a:['Природа важна?','Почему мир такой красивый?','Если участок затенить, средняя температура поверхности снизится','Все должны сортировать мусор'],c:2,d:2,t:'Сложно',e:'Гипотеза связывает измеряемые переменные и допускает проверку наблюдением или экспериментом.'},
];
const state={xp:Number(localStorage.getItem('eco_xp')||0),answered:Number(localStorage.getItem('eco_answered')||0),correct:Number(localStorage.getItem('eco_correct')||0),days:JSON.parse(localStorage.getItem('eco_days')||'{}')};
const save=()=>{localStorage.setItem('eco_xp',String(state.xp));localStorage.setItem('eco_answered',String(state.answered));localStorage.setItem('eco_correct',String(state.correct));localStorage.setItem('eco_days',JSON.stringify(state.days));};
function show(view){$$('.view').forEach(v=>v.classList.remove('active'));$('#view-'+view)?.classList.add('active');$$('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));history.replaceState(null,'','#'+view);window.scrollTo({top:0,behavior:'smooth'});if(view==='progress')renderProgress();}
document.addEventListener('click',e=>{const v=e.target.closest('[data-view]');if(v){e.preventDefault();show(v.dataset.view)}const l=e.target.closest('[data-lesson]');if(l)openLesson(l.dataset.lesson)});
$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('eco_theme',document.body.classList.contains('dark')?'dark':'light')});if(localStorage.getItem('eco_theme')==='dark')document.body.classList.add('dark');
function renderLessons(filter='ALL'){const grid=$('#lessonGrid');grid.textContent='';lessons.filter(x=>filter==='ALL'||x.tag===filter).forEach(x=>{const a=document.createElement('article');a.className='lesson-card';const r=document.createElement('span');r.className='region';r.textContent=x.region;const h=document.createElement('h3');h.textContent=x.title;const p=document.createElement('p');p.textContent=x.text;const b=document.createElement('button');b.className='text-btn';b.dataset.lesson=x.id;b.textContent='Открыть кейс →';a.append(r,h,p,b);grid.append(a)});}
function renderFilters(){const f=$('#lessonFilters');['ALL','ЯМАЛ','РОССИЯ','МИР'].forEach((x,i)=>{const b=document.createElement('button');b.className='filter'+(!i?' active':'');b.textContent=x==='ALL'?'Все темы':x;b.onclick=()=>{$$('.filter').forEach(z=>z.classList.remove('active'));b.classList.add('active');renderLessons(x)};f.append(b)})}
function openLesson(id){const x=lessons.find(z=>z.id===id);if(!x)return;const d=$('#lessonDetail');d.textContent='';const p=document.createElement('p');p.className='eyebrow';p.textContent=x.region+' / '+x.level;const h=document.createElement('h1');h.textContent=x.title;const lead=document.createElement('p');lead.className='lead';lead.textContent=x.text;const fact=document.createElement('div');fact.className='fact';fact.innerHTML='<strong>Как исследовать:</strong> ищи первичные данные, смотри период наблюдения и не сравнивай показатели с разными методиками без оговорки.';const src=document.createElement('p');src.className='source';src.textContent='Источник: '+x.source+' ';const a=document.createElement('a');a.href=x.url;a.target='_blank';a.rel='noopener noreferrer';a.textContent='Открыть источник';src.append(a);d.append(p,h,lead,fact,src);show('lesson');}
function setupQuiz(){const q=$('#quizSetup');q.innerHTML='<h2>Выбери режим</h2><div class="setup-row" id="diff"><button class="choice selected" data-d="0">Базовый</button><button class="choice" data-d="1">Исследователь</button><button class="choice" data-d="2">Эксперт</button></div><div class="setup-row" id="topic"><button class="choice selected" data-t="ALL">Все темы</button><button class="choice" data-t="ЯНАО">Ямал</button><button class="choice" data-t="Россия">Россия</button><button class="choice" data-t="Мир">Мир</button><button class="choice" data-t="Метод">Метод</button></div><button class="primary" id="startQuiz">Запустить 5 вопросов →</button>';let diff=0,topic='ALL';$$('#diff .choice').forEach(b=>b.onclick=()=>{$$('#diff .choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');diff=Number(b.dataset.d)});$$('#topic .choice').forEach(b=>b.onclick=()=>{$$('#topic .choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');topic=b.dataset.t});$('#startQuiz').onclick=()=>startQuiz(diff,topic);}
function startQuiz(diff,topic){let pool=questions.filter(x=>(topic==='ALL'||x.t===topic)&&x.d<=diff);if(pool.length<5)pool=questions.filter(x=>topic==='ALL'||x.t===topic);pool=[...pool].sort(()=>Math.random()-.5).slice(0,5);let i=0,score=0;const area=$('#quizArea');area.classList.remove('hidden');function next(){if(i>=pool.length){state.xp+=score;save();area.innerHTML='<div class="quiz-q"><p class="eyebrow">SESSION COMPLETE</p><h2>Готово. +'+score+' XP</h2><p>Правильных ответов: '+state.correct+' из '+state.answered+' за всё время.</p><button class="primary" id="again">Ещё раунд</button></div>';$('#again').onclick=()=>{area.classList.add('hidden');setupQuiz()};return}const x=pool[i];area.innerHTML='';const box=document.createElement('div');box.className='quiz-q';const meta=document.createElement('div');meta.className='quiz-meta';meta.innerHTML='<span>ВОПРОС '+(i+1)+' / '+pool.length+'</span><span>'+(['Базовый','Исследователь','Эксперт'][x.d])+'</span>';const h=document.createElement('h2');h.textContent=x.q;const answers=document.createElement('div');answers.className='answers';x.a.forEach((txt,n)=>{const b=document.createElement('button');b.className='answer';b.textContent=txt;b.onclick=()=>{if(answers.dataset.done)return;answers.dataset.done='1';state.answered++;const ok=n===x.c;if(ok){b.classList.add('correct');score+=10*(x.d+1);state.correct++}else{b.classList.add('wrong');answers.children[x.c].classList.add('correct')}save();const e=document.createElement('p');e.style.color='#b8c6bd';e.textContent=x.e;box.append(e);const cont=document.createElement('button');cont.className='primary';cont.textContent='Следующий →';cont.onclick=next;box.append(cont)};answers.append(b)});box.append(meta,h,answers);area.append(box);i++}next();}
function renderLab(){const a=$('#labArea');a.innerHTML='';const c=document.createElement('article');c.className='lab-card';c.innerHTML='<p class="eyebrow">CASE / URBAN HEAT</p><h2>Ты наблюдаешь: площадь с асфальтом нагревается сильнее газона.</h2><p>Какой следующий шаг превращает наблюдение в исследование?</p>';['Сразу объявить причиной только асфальт.','Измерить температуру поверхностей в сопоставимых условиях и повторить наблюдения.','Спросить, какая поверхность выглядит красивее.'].forEach((t,i)=>{const b=document.createElement('button');b.className='lab-option';b.textContent=t;b.onclick=()=>{a.querySelectorAll('.lab-option').forEach(x=>x.disabled=true);const r=document.createElement('p');r.textContent=i===1?'Верно: сравнение условий и повторяемость делают гипотезу проверяемой.':'Не совсем. Сначала нужны измерения и сопоставимые условия.';r.style.fontWeight='700';a.append(r);if(i===1){state.xp+=20;save()}};c.append(b)});a.append(c);const c2=document.createElement('article');c2.className='lab-card';c2.innerHTML='<p class="eyebrow">SOURCE CHECK</p><h2>Мини-аудит числа</h2><p>Перед тем как довериться экологическому показателю, проверь четыре вещи.</p><p><strong>1.</strong> Единицы · <strong>2.</strong> Период · <strong>3.</strong> Метод · <strong>4.</strong> Первичный источник</p>';a.append(c2);}
function renderProgress(){const a=$('#progressArea');const pct=state.answered?Math.round(state.correct/state.answered*100):0;a.innerHTML='<div class="progress-card"><p class="eyebrow">XP</p><div class="xp">'+state.xp+'</div><p>Фиксированные баллы за действия. Уровень не зависит от случайности.</p><div class="bar"><i style="width:'+Math.min(100,state.xp%100)+'%"></i></div></div><div class="progress-card"><p class="eyebrow">QUIZ ACCURACY</p><h2>'+pct+'%</h2><p>Правильных: '+state.correct+' · Отвечено: '+state.answered+'</p></div><div class="progress-card"><p class="eyebrow">7-DAY FIELD LOG</p><div id="days"></div></div>';const days=$('#days');for(let i=0;i<7;i++){const d=new Date();d.setDate(d.getDate()-i);const key=d.toISOString().slice(0,10);const row=document.createElement('label');row.className='challenge';const cb=document.createElement('input');cb.type='checkbox';cb.checked=!!state.days[key];cb.onchange=()=>{state.days[key]=cb.checked;save()};const t=document.createElement('span');t.textContent=i===0?'Сегодня: найди один предмет, который можно повторно использовать.':i===1?'Вчера: запиши одно наблюдение о природе без оценки.':['Позавчера: проверь источник экологического утверждения.','День 4: найди единицу измерения в экологическом графике.','День 5: сравни две точки наблюдения.','День 6: задай вопрос, на который можно собрать данные.','День 7: объясни экологическое явление одним абзацем.'][i-2];row.append(cb,t);days.append(row)}}
async function loadLive(){const utc=$('#utcNow');setInterval(()=>utc.textContent=new Date().toISOString().replace('T',' ').slice(0,19)+' UTC',1000);try{const r=await fetch('https://services.swpc.noaa.gov/products/solar-wind/plasma-7-day.json',{cache:'no-store'});if(!r.ok)throw new Error();const j=await r.json();const row=j.at(-1);const speed=Number(row[2]);if(Number.isFinite(speed)){$('#solarSpeed').textContent=Math.round(speed);$('#solarSpeedStatus').textContent='Получено '+new Date().toLocaleTimeString('ru-RU')}}catch{$('#solarSpeed').textContent='—';$('#solarSpeedStatus').textContent='Источник недоступен'}}
(async()=>{try{const r=await fetch('https://services.swpc.noaa.gov/products/noaa-planetary-k-index.json',{cache:'no-store'});if(!r.ok)throw new Error();const j=await r.json();const row=j.at(-1);const kp=Number(row[1]);$('#kpNow').textContent=Number.isFinite(kp)?kp.toFixed(1):'—';$('#kpStatus').textContent='NOAA · актуальный feed'}catch{$('#kpNow').textContent='—';$('#kpStatus').textContent='Источник недоступен'}})();
renderFilters();renderLessons();setupQuiz();renderLab();loadLive();if(location.hash)show(location.hash.slice(1));
